# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Pipeline Tests

on:
  #schedule:
    #- cron:  '35 3 * * *'
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  Test:
    runs-on: windows-latest
    steps:
    - uses: browser-actions/setup-chrome@v1
      with:
       chrome-version: 126
       install-chromedriver: true
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - uses: actions/upload-artifact@v4
      if: always()
      with: 
        name: Reports
        path: D:\a\1CrmCloud\1CrmCloud\DemoAutomation/bin/Debug/net8.0/Reports
